services:
  hub:
    image: selenium/hub:4.32
  chrome:
    image: selenium/node-chromium:4.32
    shm_size: '2g'
    depends_on:
    - hub
    # Below create mutiple replica of service
    deploy:
      replicas: 3
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_MAX_SESSIONS=4
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_VNC_NO_PASSWORD=1
  firefox:
    image: selenium/node-firefox:4.32
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 3
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_MAX_SESSIONS=4
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_VNC_NO_PASSWORD=1
  vendor-portal:
    image: veereshchetti/selenium-docker
    depends_on:
    - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output 
  flight-reservation:
    image: veereshchetti/selenium-docker
    depends_on:
    - firefox
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - ./output/flight-reservation:/home/selenium-docker/test-output   